import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { readFileSync, mkdtempSync, mkdirSync, copyFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { test } from 'node:test';
import { inflateSync } from 'node:zlib';

const root = new URL('../', import.meta.url);
const css = readFileSync(new URL('src/app/globals.css', root), 'utf8');
const texture = css.match(/--paper-texture:\s*url\(['"]\/(.*?)['"]\)/)[1];
const paper = [...Buffer.from(css.match(/--paper:\s*#([\da-f]{6})/i)[1], 'hex')];

test('ordinary paper remains pale and subtly textured without browser blending', () => {
  const png = readFileSync(new URL(`public/${texture}`, root));
  const width = png.readUInt32BE(16), height = png.readUInt32BE(20);
  assert.equal(png[24], 8, 'eight-bit pixels');
  assert.equal(png[25], 6, 'RGBA texture');
  const chunks = [];
  for (let offset = 8; offset < png.length;) {
    const length = png.readUInt32BE(offset);
    if (png.toString('ascii', offset + 4, offset + 8) === 'IDAT') chunks.push(png.subarray(offset + 8, offset + 8 + length));
    offset += length + 12;
  }
  const rows = inflateSync(Buffer.concat(chunks));
  const totals = [0, 0, 0], min = [255, 255, 255], max = [0, 0, 0];
  for (let y = 0; y < height; y++) {
    const row = y * (width * 4 + 1);
    assert.equal(rows[row], 0, 'generated texture uses unfiltered scanlines');
    for (let x = 0; x < width; x++) {
      const offset = row + 1 + x * 4;
      assert.equal(rows[offset + 3], 255, 'paper pixels must be opaque, not raw translucent noise');
      for (let c = 0; c < 3; c++) {
        const value = rows[offset + c];
        totals[c] += value; min[c] = Math.min(min[c], value); max[c] = Math.max(max[c], value);
      }
    }
  }
  for (const [c, base] of paper.entries()) {
    assert(Math.abs(totals[c] / (width * height) - base) < 1, 'match the configured paper color');
    assert(max[c] - min[c] > 0 && max[c] - min[c] <= 25, 'retain subtle grain without snow-like contrast');
  }
});

test('committed paper assets can be regenerated byte for byte', () => {
  const directory = mkdtempSync(join(tmpdir(), 'kaiwa-paper-'));
  try {
    mkdirSync(join(directory, 'scripts'));
    mkdirSync(join(directory, 'public'));
    const generator = join(directory, 'scripts/generate-paper-grain.mjs');
    copyFileSync(new URL('scripts/generate-paper-grain.mjs', root), generator);
    execFileSync(process.execPath, [generator]);
    for (const name of new Set([texture, 'paper-grain.png'])) {
      assert.deepEqual(readFileSync(join(directory, 'public', name)), readFileSync(new URL(`public/${name}`, root)));
    }
  } finally {
    rmSync(directory, { recursive: true, force: true });
  }
});
